name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install packages
        run: |
          brew update
          brew unlink python3
          # upgrade from python@3.12 to python@3.12.2 fails to overwrite those
          rm -f /usr/local/bin/2to3 /usr/local/bin/2to3-3.12 /usr/local/bin/idle3 /usr/local/bin/idle3.12 /usr/local/bin/pydoc3 /usr/local/bin/pydoc3.12 /usr/local/bin/python3 /usr/local/bin/python3-config /usr/local/bin/python3.12 /usr/local/bin/python3.12-config
          brew install gcovr ninja libmagic
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      - name: Install python modules
        run: pip3 install meson==0.49.2 pytest

      - name: Install dependencies
        uses: kiwix/kiwix-build/actions/dl_deps_archive@main
        with:
          os_name: macos
          target_platform: native_dyn

      - name: Compile
        shell: bash
        run: |
          export PKG_CONFIG_PATH=$HOME/BUILD_native_dyn/INSTALL/lib/pkgconfig
          export CPPFLAGS="-I$HOME/BUILD_native_dyn/INSTALL/include"
          meson . build
          cd build
          ninja


  Linux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - native_static
          - native_dyn
          - win32_static
          - win32_dyn
        include:
          - target: native_static
            image_variant: focal
            lib_postfix: '/x86_64-linux-gnu'
          - target: native_dyn
            image_variant: focal
            lib_postfix: '/x86_64-linux-gnu'
          - target: win32_static
            image_variant: f35
            lib_postfix: '64'
          - target: win32_dyn
            image_variant: f35
            lib_postfix: '64'

    env:
      HOME: /home/runner
    runs-on: ubuntu-22.04
    container:
      image: "ghcr.io/kiwix/kiwix-build_ci_${{matrix.image_variant}}:2023-10-30"
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: kiwix/kiwix-build/actions/dl_deps_archive@main
      with:
        target_platform: ${{ matrix.target }}
    - name: Compile
      shell: bash
      run: |
        if [[ "${{matrix.target}}" =~ .*_static ]]; then
          MESON_OPTION="-Dstatic-linkage=true"
        fi
        if [[ ! "${{matrix.target}}" =~ native_.* ]]; then
          MESON_OPTION="$MESON_OPTION --cross-file $HOME/BUILD_${{matrix.target}}/meson_cross_file.txt"
        fi
        meson . build ${MESON_OPTION} -Db_coverage=true
        cd build
        ninja
      env:
        PKG_CONFIG_PATH: "${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/lib/pkgconfig:${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/lib${{matrix.lib_postfix}}/pkgconfig"
        CPPFLAGS: "-I${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/include"
    - name: Test
      shell: bash
      run: |
       cd build
       meson test --verbose
       ninja coverage
      env:
        LD_LIBRARY_PATH: "${{env.HOME}}/BUILD_${{matrix.target}}/INSTALL/lib${{matrix.lib_postfix}}"
    - name: Publish coverage
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
